# Generated by Django 2.2 on 2021-07-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_who_granted',
        ),
        migrations.AddField(
            model_name='wish',
            name='users_who_granted',
            field=models.ManyToManyField(related_name='wish_granted', to='table_app.User'),
        ),
    ]
