# Generated by Django 2.2 on 2021-07-21 05:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('ojbects', django.db.models.manager.Manager()),
            ],
        ),
    ]
