# Generated by Django 2.2 on 2021-07-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books_app', '0002_auto_20210721_0548'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
    ]
