# Generated by Django 2.2 on 2021-06-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210630_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emaill_address',
            new_name='email_address',
        ),
    ]
