# Generated by Django 2.2 on 2021-07-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20210630_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default='Boston', max_length=255),
            preserve_default=False,
        ),
    ]
