# Generated by Django 2.2 on 2021-08-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camped_app', '0003_auto_20210805_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
