# Generated by Django 2.2 on 2021-08-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camped_app', '0004_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('attendee', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('camped_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_camped', to='camped_app.User')),
                ('camped_join', models.ManyToManyField(related_name='user_joined', to='camped_app.User')),
            ],
        ),
    ]
