# Generated by Django 2.2 on 2021-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camped_app', '0005_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='end_date',
            field=models.DateField(default=True),
            preserve_default=False,
        ),
    ]
