# Generated by Django 2.2 on 2021-07-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo',
            new_name='dojos',
        ),
    ]
