# Generated by Django 2.2 on 2021-07-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20210708_0438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ninjas',
            new_name='ninja',
        ),
    ]
