# Generated by Django 2.2 on 2021-07-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0004_auto_20210710_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojos',
            new_name='dojo',
        ),
    ]
