# Generated by Django 2.2 on 2021-07-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_wish_granted_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_who_liked',
        ),
    ]
